In [2]:
import numpy as np

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr.shape

(2, 2, 3)

In [ ]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr0 = arr[0]
arr0


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr0[:1,:2]

array([[1, 2]])

In [4]:
ar = np.empty((2,3,4))
ar

array([[[-0.25, -0.5 ,  0.  , -0.25],
        [ 0.25, -0.5 ,  0.5 , -0.25],
        [ 0.25,  0.  ,  0.5 ,  0.25]],

       [[ 0.25,  0.5 ,  0.  ,  0.25],
        [-0.25,  0.5 , -0.5 ,  0.25],
        [-0.25,  0.  , -0.5 , -0.25]]])

In [8]:
for i in np.arange(2):
  print("i",i)
  for j in range(3):
    print("j", j)
    ar[i][j] = i*j
    print(ar[i][j])
print(ar)

i 0
j 0
[0. 0. 0. 0.]
j 1
[0. 0. 0. 0.]
j 2
[0. 0. 0. 0.]
i 1
j 0
[0. 0. 0. 0.]
j 1
[1. 1. 1. 1.]
j 2
[2. 2. 2. 2.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [2. 2. 2. 2.]]]


In [11]:
ar[1,2]

array([2., 2., 2., 2.])

In [12]:
ar[1][2]

array([2., 2., 2., 2.])

In [13]:
ar[1][2][0]

2.0

In [14]:
ar.T

array([[[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]]])

In [ ]:
ar.T.shape

(4, 3, 2)

In [ ]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ar1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
np.dot(ar1.T, ar1)   #ظرب ماتریسی

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [ ]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.where(ar1 >2,1,0)

array([[0, 0, 1],
       [1, 1, 1]])

In [ ]:
np.arange(-3,3,0.3)

array([-3.00000000e+00, -2.70000000e+00, -2.40000000e+00, -2.10000000e+00,
       -1.80000000e+00, -1.50000000e+00, -1.20000000e+00, -9.00000000e-01,
       -6.00000000e-01, -3.00000000e-01, -1.77635684e-15,  3.00000000e-01,
        6.00000000e-01,  9.00000000e-01,  1.20000000e+00,  1.50000000e+00,
        1.80000000e+00,  2.10000000e+00,  2.40000000e+00,  2.70000000e+00])

In [ ]:
(ar1>1).sum()

5

In [ ]:
ar1>1

array([[False,  True,  True],
       [ True,  True,  True]])

In [ ]:
ar2 = np.array([1,1,2,3,4,4,5,5,0,0])
np.unique(ar2)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.random.randn(4)

array([-0.63766075,  0.15501242, -0.46128531, -0.73595188])

In [ ]:
np.save('some_array',ar1)

In [ ]:
np.savez('some_array_z.npz', a = ar1)

In [ ]:
np.load('some_array.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arch = np.load('some_array_z.npz')
print(arch)

In [ ]:
np.random.randn(10)

array([-0.40337923,  0.0847857 ,  0.63695745,  1.3153874 ,  0.35485002,
       -1.66381719,  0.9938321 , -0.18301631,  0.07914133,  1.25923353])

In [ ]:
np.random.uniform(1,5,10)

array([2.87532884, 4.8733867 , 1.64961542, 4.26719232, 1.65377656,
       4.46430615, 4.30945754, 3.7229181 , 4.09212025, 4.7741932 ])

In [ ]:
np.random.chisquare(5, size = 20)

array([ 2.83412147,  3.75308577,  1.9632916 ,  3.68316962,  3.05967839,
        9.67686414,  1.04939079,  5.9132386 ,  1.83266534,  0.52842552,
       13.12316923,  4.95193396,  4.49245336,  2.77652967,  4.45278722,
        4.75587717,  2.54337578,  3.60679483,  2.78788121, 10.41315219])

In [ ]:
np.random.rand(10)

array([0.52405596, 0.46178949, 0.50587675, 0.74906072, 0.15380586,
       0.96364712, 0.28701382, 0.80206995, 0.3312666 , 0.73944269])

In [ ]:
np.dot(ar1, ar1.T)

array([[14, 32],
       [32, 77]])

In [ ]:
ar1.dot(ar1.T)

array([[14, 32],
       [32, 77]])

In [ ]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [ ]:
np.exp(ar1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
ar1.any()

True

In [ ]:
ar1.all()

True

In [ ]:
np.unique(ar1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.mean(ar1)

3.5

In [ ]:
np.average(ar1)

3.5

In [ ]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
ar3 = np.array([7,8,9])

np.ix_(ar1,ar2, ar3)

(array([[[1]],
 
        [[2]],
 
        [[3]]]),
 array([[[4],
         [5],
         [6]]]),
 array([[[7, 8, 9]]]))