In [1]:
import numpy as np

In [5]:
arr = np.array([1,1,2,0,3,3,1,4,4,4,55,4,1,0,0,1])

count the frequency of a members in an array

In [7]:
np.bincount(arr)

array([3, 5, 1, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [8]:
arr.shape

(16,)

In [12]:
arr1 = arr.reshape((2,2,4))
arr1

array([[[ 1,  1,  2,  0],
        [ 3,  3,  1,  4]],

       [[ 4,  4, 55,  4],
        [ 1,  0,  0,  1]]])

In [16]:
arr1[:,1]

array([[3, 3, 1, 4],
       [1, 0, 0, 1]])

In [19]:
arr1[:,[1]]

array([[[3, 3, 1, 4]],

       [[1, 0, 0, 1]]])

concatenate

In [27]:
np.concatenate((arr1[0], arr1[1]),axis = 1)

array([[ 1,  1,  2,  0,  4,  4, 55,  4],
       [ 3,  3,  1,  4,  1,  0,  0,  1]])

In [28]:
np.concatenate((arr1[0], arr1[1]),axis = 0)

array([[ 1,  1,  2,  0],
       [ 3,  3,  1,  4],
       [ 4,  4, 55,  4],
       [ 1,  0,  0,  1]])

Vectorization

In [32]:
def add(arr1, arr2):
    return arr1 + arr2

result = np.vectorize(add)
result(arr1[0],arr1[1])

array([[ 5,  5, 57,  4],
       [ 4,  3,  1,  5]])

In [38]:
np.vstack(arr)

array([[ 1],
       [ 1],
       [ 2],
       [ 0],
       [ 3],
       [ 3],
       [ 1],
       [ 4],
       [ 4],
       [ 4],
       [55],
       [ 4],
       [ 1],
       [ 0],
       [ 0],
       [ 1]])

In [39]:
np.split(arr,2)

[array([1, 1, 2, 0, 3, 3, 1, 4]), array([ 4,  4, 55,  4,  1,  0,  0,  1])]

string

In [50]:
arra = np.array(['ali','haMID','Saied','Setare'])

In [51]:
np.char.upper(arra)

array(['ALI', 'HAMID', 'SAIED', 'SETARE'], dtype='<U6')

In [52]:
np.char.lower(arra)

array(['ali', 'hamid', 'saied', 'setare'], dtype='<U6')

In [53]:
np.char.swapcase(arra)

array(['ALI', 'HAmid', 'sAIED', 'sETARE'], dtype='<U6')

In [55]:
np.char.title(arra)

array(['Ali', 'Hamid', 'Saied', 'Setare'], dtype='<U6')

In [56]:
np.char.capitalize(arra)

array(['Ali', 'Hamid', 'Saied', 'Setare'], dtype='<U6')

اضافه کردن صفر پشت عدد

In [64]:
array = np.array(['1','12','345', '654'])

In [65]:
np.char.zfill(array,4)

array(['0001', '0012', '0345', '0654'], dtype='<U4')

In [69]:
np.char.join(" ",array)

array(['1', '1 2', '3 4 5', '6 5 4'], dtype='<U5')

In [68]:
np.char.multiply(array,2)

array(['11', '1212', '345345', '654654'], dtype='<U6')

In [71]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

pad

In [73]:
one = np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
np.pad(one,constant_values = 0, pad_width = 2)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
#it returns size of integer or string in the array:
array.itemsize

12