In [1]:
import numpy as np

In [30]:
arr = np.array([[[1,2,5],[3,4,6]],[[5,6,7],[7,8,9]]])
print('shape:', arr.shape,'\n')
print(arr)

shape: (2, 2, 3) 

[[[1 2 5]
  [3 4 6]]

 [[5 6 7]
  [7 8 9]]]


In [31]:
arr[::-1]

array([[[5, 6, 7],
        [7, 8, 9]],

       [[1, 2, 5],
        [3, 4, 6]]])

In [19]:
zero = np.zeros((2,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
zero[1,:2,:3]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
random_num = np.random.random(4)   #return several random numbers between 0 and 1
random_num

array([0.35467444, 0.29407443, 0.33210616, 0.39218356])

In [41]:
np.mean(random_num)

0.4197273919969854

In [42]:
import random

In [50]:
random.randint(1,12)

4

In [47]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [51]:
random.sample(range(1,10),5)    #return several random numbers from a list

[8, 6, 9, 1, 3]

In [55]:
one = np.ones((3,2,4))
one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [57]:
arr1 =np.ones((2,3))
arr2 = np.ones((3,2))

In [58]:
np.dot(arr1,arr2)

array([[3., 3.],
       [3., 3.]])

In [60]:
arr

array([[[1, 2, 5],
        [3, 4, 6]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [61]:
arr.shape

(2, 2, 3)

In [62]:
arr.T.shape

(3, 2, 2)

In [65]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr3.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
import pandas as pd

In [72]:
df = pd.DataFrame(arr3,columns = ['a','b','c'], index = [1,2])
df

a  b  c
1  1  2  3
2  4  5  6

In [77]:
date = ['Monday','Tuesday','Wednesday','Thursday', 'Friday','Saturday','Sunday']


In [88]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [90]:
df1 = pd.DataFrame(date)
df1['num'] = np.arange(7)

In [98]:
df1.rename_axis(['index'])
df1.rename(columns = {0: 'e'})

e  num
0     Monday    0
1    Tuesday    1
2  Wednesday    2
3   Thursday    3
4     Friday    4
5   Saturday    5
6     Sunday    6